### ISSUE TITLE
pycurl ssl error on windows

### ISSUE THREAD

**Issue by JohnDzialo** [tus/tus-py-client#11]
Hi Guys,

I am compiling an exe using pyinstaller 3.3 on Windows Server 2016, with Windows 10 SDK installed.  This is a simple python 3.6.2 app importing tuspy 0.1 using pycurl 7.46.0.

60, SSL certificate problem: unable to get local issuer certificate

Obviously pycurl can't find my cert to compare against the url I am passing to tuspy which is https.  

How can i...

a) turn off ssl verification with my call to tuspy
b) inform tuspy of the location of a valid cert file
c) fix this some other way

Thanks!!

**Comment by ifedapoolarewaju** [comment]
Hi @JohnDzialo , thank you for reporting this. 🙂 I have added a fix and published a released at `v0.1.2`.

**Comment by ifedapoolarewaju** [comment]
I would close this now. Please feel free to reopen this, if the issue persists 🙂
