### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by olucurious** [tus/tus-py-client#13]
I've been getting this error for a few days now whenever I try to install tuspy with pip

Collecting tuspy
  Using cached tuspy-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-MLntjw/tuspy/setup.py", line 16, in <module>
        long_description = open('README.md').read()
    IOError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-MLntjw/tuspy/

**Comment by ifedapoolarewaju** [comment]
Hi @olucurious, thank you for reporting this. The issue has been fixed [here](https://github.com/tus/tus-py-client/releases/tag/v0.1.3) and a new version has been released. :)

Please run `pip install tuspy==0.1.3`
