### ISSUE TITLE
Using the `Uploader` class directly fails because of no headers

### ISSUE THREAD

**Issue by peixian** [tus/tus-py-client#14]
When using the `uploader.py` file like so:

```
from tusclient.uploader import Uploader

my_uploader = Uploader('path/to/file.ext',
                       url='http://master.tus.io/files/abcdef123456',
                       chunk_size=200)
```

a `'NoneType' object has no attribute 'headers'` error is raised. This is because `self.headers` is never set, resulting in the error when `self.getoffset()` is called: https://github.com/tus/tus-py-client/blob/master/tusclient/uploader.py#L92

**Comment by ifedapoolarewaju** [comment]
@peixian thank you for reporting. I'll work on this, but please also feel free to submit a PR :)

**Comment by ifedapoolarewaju** [comment]
this issue is fixed [here](https://github.com/tus/tus-py-client/releases/tag/v0.2.1)
