### ISSUE TITLE
Support the Upload-Checksum extension

### ISSUE THREAD

**Issue by bratao** [tus/tus-py-client#25]
This is a very important feature of the tus protocol. 

https://tus.io/protocols/resumable-upload.html#checksum

**Comment by mochic** [comment]
could put in a pr for this if im not stepping on toes

**Comment by ifedapoolarewaju** [comment]
@mochic please feel free to submit a PR. I'll be happy to review :)

**Comment by bratao** [comment]
@mochic this would be very very nice. I was about to start this feature on my own when I have free time. But this may take a while.

This client have it implemented, it is very straightforward https://github.com/everydo/tusclient
