### ISSUE TITLE
Turning off the certificate check 

### ISSUE THREAD

**Issue by AkbarAlam** [tus/tus-py-client#29]
I have used the Node client of the Tus Client, There was an issue with certificate. I have turned it off with the following code 
```
const process = require('process')

process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0
```

How can I do it in Python Client ? 

this is the error I am getting

> (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

**Comment by ifedapoolarewaju** [comment]
Hi @AkbarAlam,

you can try this in your code before starting your tus upload

```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by ifedapoolarewaju** [comment]
I'll close this issue now. If my comment above does not solve the problem, then please feel free to re-open this issue :)
