### ISSUE TITLE
Lastest Version doesn't support upload_checksum of the Class Uploader

### ISSUE THREAD

**Issue by susufqx** [tus/tus-py-client#32]
Hello,

I have installed tuspy v0.2.3, but it doesn't support the attribute upload_checksum in the class Uploader. I found that the newest code does not be released.

**Comment by Acconut** [comment]
@ifedapoolarewaju Would you mind having a look at this?

**Comment by ifedapoolarewaju** [comment]
it's released to v0.2.4 now
