### ISSUE TITLE
how to get response and location of upload in tus server?

### ISSUE THREAD

**Issue by 6273parastu** [tus/tus-py-client#36]
from tusclient.request import TusRequest
from tusclient import client
my_client = client.TusClient('https://master.tus.io/files/')       
    uploader = my_client.uploader(f'C:/Users/parastu/Documents/upload_vod/videos/1.MP4', chunk_size=20000000)
    fs = open(f'C:/Users/parastu/Documents/upload_vod/videos/1.MP4','rb')
    uploader = my_client.uploader(file_stream=fs, chunk_size=20000000)
    uploader.upload()
    request_tus = TusRequest(uploader)
    response_tus = request_tus.response_content

**when i upload video , i don't know how to get response and location of upload in tus server, in this code "request_tus " return none object, please help me.**

**Comment by Acconut** [comment]
@ifedapoolarewaju Could you have a look at this?

**Comment by 6273parastu** [comment]
@Acconut do you know how to send post request to tus server and get response for e.g https://tus.io/demo.html ,i  just  want get location url for upload

**Comment by ifedapoolarewaju** [comment]
Hi @6273parastu the location of the upload will be at `uploader.url`. I apologise that the documentation doesn't provide a clear info indicating that.
