### ISSUE TITLE
Release of a new version

### ISSUE THREAD

**Issue by kad-wenner** [tus/tus-py-client#45]
Dear authors,

We have been using your package (quite satisfactory!) for a while now. Recently, we transitioned to using your package behind a corporate proxy. This led to some issues which were already outlined in this PR: https://github.com/tus/tus-py-client/pull/34 

Obviously we were happy with that fix, but it was a tad dissapointing that this fix is not on the PyPI repositories. For now we fixed this by grabbing a local version of this repository, but we are wondering: Are there any plans to release a new version on PYPI with recent changes?

Kind regards, 

Rob

**Comment by GideonGiacomelli** [comment]
Dear authors,

we have the same problem on our side. We would be happy to help where we can to get a new version released. Please get in touch with me any time.

Best regards,
Gideon

**Comment by ifedapoolarewaju** [comment]
this has now been released to v0.2.5. Sincere apologies for the delay here 🙏🏽 , and thank you for the nudge! 😃

**Comment by GideonGiacomelli** [comment]
Thank you, Ifedapo. 😃
