### ISSUE TITLE
Cryptic stacktrace when trying to start upload

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [tus/tus-py-client#46]
I am trying to upload a file to Cloudflare Stream while following [their documentation](https://developers.cloudflare.com/stream/uploading-videos/upload-video-file#command-line-example) and they suggest the following command:
```
tus-upload --chunk-size 52428800 --header Authorization "Bearer {mytoken}" "{myfile}" https://api.cloudflare.com/client/v4/accounts/{myaccountid}/stream
```

Running this, I get the following stacktrace:
```
[2021-08-02 20:39:28,370] INFO Creating file endpoint
Traceback (most recent call last):
  File "/home/pi/.local/bin/tus-upload", line 10, in <module>
    sys.exit(_cmd_upload())
  File "/home/pi/.local/lib/python3.7/site-packages/tus.py", line 101, in _cmd_upload
    metadata=args.metadata)
  File "/home/pi/.local/lib/python3.7/site-packages/tus.py", line 208, in create
    raise TusError("Create failed", response=response)
tus.TusError: <exception str() failed>
```

This doesn't really tell me much so I don't know how to go about troubleshooting this without attaching a debugger. The only issue I can think of is that I'm using a Raspberry Pi which has an ARM CPU.

Either way, there should probably be a better exception message so this is easier to debug by an end-user.

**Comment by HoLLy-HaCKeR** [comment]
Looks like the cause for my error was because of an incorrect authorization header. I used another library which gave me information on the response from the server:
```
(node:26415) UnhandledPromiseRejectionWarning: Error: tus: failed to create upload, caused by Error: tus: unexpected response while creating upload, originated from request (method: POST, url: https://api.cloudflare.com/client/v4/accounts/[...]/stream, response code: 401, response text: {"success":false,"errors":[{"code":10000,"message":"Authentication error"}]} [...]
```

I don't need a resolution to this issue so feel free to close it if you don't feel this is necessary.

**Comment by Acconut** [comment]
Glad to read that you found the issue :+1:
