### ISSUE TITLE
Release A new version to pip?

### ISSUE THREAD

**Issue by honglei** [tus/tus-py-client#61]
The news pip version is 0.2.5 which not support async_upload one-year ago，so, hope a new version on pip site.

**Comment by Acconut** [comment]
Good point, we will have a look. @kiloreux, do you have permissions to push to https://pypi.org/project/tuspy/ on Pip?

**Comment by kiloreux** [comment]
Yes, I do have it, would you like me to grant it to you?

**Comment by Acconut** [comment]
@kiloreux Could you add tus-bot on PyPI to the tuspy package? Also, I have just setup this repo for v1.0.0. Could you push that one to PyPI please?

**Comment by kiloreux** [comment]
@Acconut, do you think we should automate the release process with PyPi?

**Comment by Acconut** [comment]
Yes, automated releases would definitely be helpful. However, I don't see it as a priority right now as long as we can manually release for now. It would be great if we could get a release out sooner than later.
