### ISSUE TITLE
Multiple file uploads

### ISSUE THREAD

**Issue by deedos** [tus/tus-py-client#83]
Hi. I use Uppy.io in webforms and I'm trying to replicate that usage with a cli interface. My use case demands metadata upload (just checked I can get that with tus-py-client!) and eventually multiple files at once.  I could not find any mention on how to achieve this last feature in this client documentation. Would that be possible ? Many thanks in advance.

**Comment by Acconut** [comment]
The tus-py-client is a more low-level upload library compared to Uppy and does not have any special feature for uploading multiple files at the same time. You can do this by starting multiple uploads at the same time, but will have to implement it on your own.
