### ISSUE TITLE
Custom error handler

### ISSUE THREAD

**Issue by NoUseFreak** [tus/tus-py-client#86]
Hi,

I want to upload using short-lived tokens. Some requests may return with a 403 status code.

Is it possible to add a custom error handler that refreshes/re-inject the new token before performing a retry?

Kind regards

**Comment by Acconut** [comment]
There is currently no such functionality inside tus-py-client. You could disable the retries and whenever an error is thrown, you catch it, generate a new token and then resume the upload. I haven't tested it, but this should allow you to implement what you want.
