### ISSUE TITLE
Typing information is not exposed (PEP 561)

### ISSUE THREAD

**Issue by nhairs** [tus/tus-py-client#87]
The typing information of this package is not available for projects that import the `tusclient` package. This is because it does not comply with [PEP 561](https://peps.python.org/pep-0561/) which requires a `py.typed` file in the root of the package.

For projects utilising MyPy this will result in the following error:

```
src/example.py:9: error: Skipping analyzing "tusclient": module is installed, but missing library stubs or py.typed marker  [import]
```

Further reading:

* https://peps.python.org/pep-0561/#packaging-type-information
* https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker

Alt titles for searchability:

* `py.typed` missing
*  not PEP 561 compliant

**Comment by Acconut** [comment]
Thanks, v1.0.2 with this improvement is released
