### ISSUE TITLE
Python client resumability question.

### ISSUE THREAD

**Issue by algsupport** [tus/tus-py-client#93]
**Question**
I have the below basice python client:

```
from tusclient import client

my_client = client.TusClient('http://localhost:9090/files/')

uploader = my_client.uploader('test.pptx', chunk_size=1000)

uploader.upload()
```

Everything seems to work as expected. But, if I stop the client execution (Ctrl+C) and then restart the exact same script without any changes whatsoever, it seems to me that the upload will start from the beginning.

Is this behavior normal?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: 32 bit Debian 5
- Used tusd version: built from main branch
- Used tusd data storage: disk store
- Used tusd configuration: ./tusd -upload-dir=./data -port 9090
- Used tus client library: tus-python-client

**Comment by Acconut** [comment]
I moved this issue into the repository for our Python client, because the question is not directly about tusd.

> Is this behavior normal?

Yes, if you want to resume uploads from a previous sessions, you must enable the storing of URLs as explained in https://tus-py-client.readthedocs.io/en/latest/#url-storage.

**Comment by algsupport** [comment]
Thank you for your help. This is very useful.
