### ISSUE TITLE
get_url missing in uploader ? 

### ISSUE THREAD

**Issue by salimkanoun** [tus/tus-py-client#95]
Hi there in the uploader class it mention a get_url method to retrieve the uploaded file url
`get_url()
Return the tus upload url.

If resumability is enabled, this would try to get the url from storage if available, otherwise it would request a new upload url from the tus server.`

But seems to be missing in the code, is it normal ? 

The internal property uploader.url is accessible an contains the url, but probably better to access it through a getter

**Comment by Acconut** [comment]
I don't see a mention of a `get_url` in the code base. Could you send a link to the corresponding code section?

**Comment by salimkanoun** [comment]
it is in the documentation : https://tus-py-client.readthedocs.io/en/latest/tusclient.html#tusclient.uploader.Uploader.get_url

**Comment by Acconut** [comment]
Ah, ok, I see. Thanks for noticing this. This documentation hasn't been updated in some time and is no longer in sync with the source code. We need to update this.

As far as I can tell, the `get_url` method was removed in 2020, although I don't know why: https://github.com/tus/tus-py-client/commit/2548bbf1552efa5d629616931e9320b1f8e9793b#diff-97989457ef05ef7429f22c43163bf6cc86bb7ae0b44379de7a06c8b35fcd8aaaL202

It's probably best and safe to directly access the `url` property for now.

**Comment by Acconut** [comment]
@ifedapoolarewaju Do you remember how the documentation on https://tus-py-client.readthedocs.io/ is generated and updated? Its content seems to be out-of-date and we would like to update it.

**Comment by ifedapoolarewaju** [comment]
I've just logged into [readTheDocs](https://app.readthedocs.org/dashboard/) and found it's me and Abdel as Maintainers.
If you share your email address via Slack, I can add you so you can take it from there.


<img width="1175" alt="image" src="https://github.com/user-attachments/assets/bb494c01-d1a4-442d-acce-d5c589b6de44">

**Comment by Acconut** [comment]
I can see in the settings that there are no webhooks or applications connected to this repository for Read The Docs. I just sent you my address on Slack, so I can take care of fixing this once I get access to the project. Thank you!

**Comment by Acconut** [comment]
The docs on https://tus-py-client.readthedocs.io/ are updated now again. Thank you for reporting this!

**Comment by salimkanoun** [comment]
Thanks for the good work you are doing !
